### ISSUE TITLE
Error at compile time: Cannot find name 'Wallet'.

### ISSUE THREAD

**Issue by jnaviask** [luniehq/cosmos-keys#11]
Using the line `
import { signWithPrivateKey, getNewWalletFromSeed } from '@lunie/cosmos-keys';` gives me the following error output.

```
ERROR in [at-loader] ./node_modules/@lunie/cosmos-keys/lib/types/cosmos-keys.d.ts:4:65 
    TS2304: Cannot find name 'Wallet'.

ERROR in [at-loader] ./node_modules/@lunie/cosmos-keys/lib/types/cosmos-keys.d.ts:6:83 
    TS2304: Cannot find name 'Wallet'.

ERROR in [at-loader] ./node_modules/@lunie/cosmos-keys/lib/types/cosmos-keys.d.ts:8:57 
    TS2304: Cannot find name 'StdSignMsg'.

ERROR in [at-loader] ./node_modules/@lunie/cosmos-keys/lib/types/cosmos-keys.d.ts:1:22 
    TS6053: File '/home/jnaviask/cw/commonwealth/node_modules/@lunie/cosmos-keys/src/cosmos-keys.d.ts' not found.
```

Looking at the package, it doesn't seem to include anything corresponding to these definitions: https://github.com/luniehq/cosmos-keys/blob/develop/src/cosmos-keys.d.ts -- should be easy to package a new version that does, though.

Thanks for your help!

**Comment by faboweb** [comment]
Would it possible for you to provide a PR with the necessary changes?

**Comment by jnaviask** [comment]
Sure, I'll do that now, but you'll have to do the `npm publish` yourself :)

**Comment by jnaviask** [comment]
Investigating further, we have two options here:
1. Publish an `@types/cosmos-keys` package containing the contents of `src/cosmos-keys.d.ts`
2. Reorganize the project to import the types directly, rather than as references to global declarations.

I'm personally in favor of the second option, and I've created the following PR which implements it: https://github.com/luniehq/cosmos-keys/pull/12
